# Example: General Usage

This example shows the general usage of `PyExperimenter`, from creating an experiment configuration file, over the actual execution of (dummy) experiments, to the extraction of experimental results. 

To execute this notebook you need to install:
```
pip install py_experimenter
pip install scikit-learn
```

## Experiment Configuration File
This notebook shows an example execution of `PyExperimenter` based on an experiment configuration file. Further explanation about the usage of `PyExperimenter` can be found in the [documentation](https://tornede.github.io/py_experimenter/usage.html).

In [1]:
import os

content = """
PY_EXPERIMENTER:
  n_jobs: 1

  Database:
    provider: sqlite
    database: py_experimenter
    table: 
      name: example_general_usage
      keyfields:
        dataset:
          type: VARCHAR(255)
          values: ['iris']
        cross_validation_splits:
          type: INT
          values: [5]
        seed:
          type: int 
          values:
            start: 2
            stop: 7
            step: 2
        kernel:
          type: VARCHAR(255)
          values: ['linear', 'poly', 'rbf', 'sigmoid']
      result_timestamps: False
      resultfields:
        pipeline: LONGTEXT
        train_f1: DECIMAL
        train_accuracy: DECIMAL
        test_f1: DECIMAL
        test_accuracy: DECIMAL

  Custom:
    datapath: sample_data
  
  CodeCarbon:
    offline_mode: False
    measure_power_secs: 25
    tracking_mode: process
    log_level: error
    save_to_file: True
    output_dir: output/CodeCarbon
"""
# Create config directory if it does not exist
if not os.path.exists('config'):
    os.mkdir('config')
    
# Create config file
experiment_configuration_file_path = os.path.join('config', 'example_general_usage.yml')
with open(experiment_configuration_file_path, "w") as f: 
  f.write(content)

## Defining the execution function

Next, the execution of a single experiment has to be defined. Note that this is a dummy example, which contains limited reasonable code. It is meant to show the core functionality of the PyExperimenter. 

The method is called with the parameters, i.e. `keyfields`, of a database entry. The results are meant to be processed to be written into the database, i.e. as `resultfields`.

In [2]:
import random
import numpy as np

from py_experimenter.result_processor import ResultProcessor

from sklearn.datasets import load_iris
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import cross_validate

def run_ml(parameters: dict, result_processor: ResultProcessor, custom_config: dict):
  seed = parameters['seed']
  random.seed(seed)
  np.random.seed(seed)

  data = load_iris()
  # In case you want to load a file from a path
  # path = os.path.join(custom_config['path'], parameters['dataset'])
  # data = pd.read_csv(path)

  X = data.data
  y = data.target

  model = make_pipeline(StandardScaler(), SVC(kernel=parameters['kernel'], gamma='auto'))  
  result_processor.process_results({
    'pipeline': str(model)
  })

  if parameters['dataset'] != 'iris':
    raise ValueError("Example error")

  scores = cross_validate(model, X, y, 
    cv=parameters['cross_validation_splits'],
    scoring=('accuracy', 'f1_micro'),
    return_train_score=True
  )
  
  result_processor.process_results({
    'train_f1': np.mean(scores['train_f1_micro']),
    'train_accuracy': np.mean(scores['train_accuracy'])
  })

  result_processor.process_results({
    'test_f1': np.mean(scores['test_f1_micro']),
    'test_accuracy': np.mean(scores['test_accuracy'])
  })

## Executing PyExperimenter

The actual execution of the PyExperimenter is done in multiple steps. 

### Initialize PyExperimenter
The PyExperimenter is initialized with the previously created configuration file. Additionally, `PyExperimenter` is given a `name`, i.e. job id, which is especially useful for parallel executions of multiple experiments on HPC.

In [3]:
from py_experimenter.experimenter import PyExperimenter

experimenter = PyExperimenter(experiment_configuration_file_path=experiment_configuration_file_path, name='example_notebook')

2025-10-07 16:52:54,990  | py-experimenter - INFO     | Found 4 keyfields
2025-10-07 16:52:54,990  | py-experimenter - INFO     | Found 5 resultfields
2025-10-07 16:52:54,991  | py-experimenter - WARNING  | No logtables given
2025-10-07 16:52:54,991  | py-experimenter - INFO     | Found 1 custom values
2025-10-07 16:52:54,991  | py-experimenter - INFO     | Found 6 codecarbon values
2025-10-07 16:52:54,992  | py-experimenter - INFO     | Initialized and connected to database

### Fill Table

The table is filled based on the above created configuration file with `fill_table_from_config()`. Therefore, the cartesian product of all keyfields makes up the content of the table. Additionally, a custom defined row, i.e. a custom defined keyfield tuple, is added with `fill_table_with_rows()`. 

Note that the table can easily be obtained as `pandas.Dataframe` via `experimenter.get_table()`.

In [4]:
experimenter.fill_table_from_config()

experimenter.fill_table_with_rows(rows=[
      {'dataset': 'error_dataset', 'cross_validation_splits': 3, 'seed': 42, 'kernel':'linear'}])

# showing database table
experimenter.get_table()

2025-10-07 16:52:54,999  | py-experimenter - INFO     | 12 rows successfully added to database. 0 rows were skipped.
2025-10-07 16:52:55,001  | py-experimenter - INFO     | 1 rows successfully added to database. 0 rows were skipped.

,ID,dataset,cross_validation_splits,seed,kernel,creation_date,status,start_date,name,machine,pipeline,train_f1,train_accuracy,test_f1,test_accuracy,end_date,error
0,1,iris,5,2,linear,2025-10-07 16:52:54,created,None,None,None,None,None,None,None,None,None,None
1,2,iris,5,4,linear,2025-10-07 16:52:54,created,None,None,None,None,None,None,None,None,None,None
2,3,iris,5,6,linear,2025-10-07 16:52:54,created,None,None,None,None,None,None,None,None,None,None
3,4,iris,5,2,poly,2025-10-07 16:52:54,created,None,None,None,None,None,None,None,None,None,None
4,5,iris,5,4,poly,2025-10-07 16:52:54,created,None,None,None,None,None,None,None,None,None,None
5,6,iris,5,6,poly,2025-10-07 16:52:54,created,None,None,None,None,None,None,None,None,None,None
6,7,iris,5,2,rbf,2025-10-07 16:52:54,created,None,None,None,None,None,None,None,None,None,None
7,8,iris,5,4,rbf,2025-10-07 16:52:54,created,None,None,None,None,None,None,None,None,None,None
8,9,iris,5,6,rbf,2025-10-07 16:52:54,created,None,None,None,None,None,None,None,None,None,None
9,10,iris,5,2,sigmoid,2025-10-07 16:52:54,created,None,None,None,None,None,None,None,None,None,None
10,11,iris,5,4,sigmoid,2025-10-07 16:52:54,created,None,None,None,None,None,None,None,None,None,None
11,12,iris,5,6,sigmoid,2025-10-07 16:52:54,created,None,None,None,None,None,None,None,None,None,None
12,13,error_dataset,3,42,linear,2025-10-07 16:52:55,created,None,None,None,None,None,None,None,None,None,None

### Execute PyExperimenter
First two randmly chosen experiments are exeecuted by setting `max_experiments=2` and `random_order=True`.

In [5]:
experimenter.execute(run_ml, max_experiments=-1)

# showing database table
experimenter.get_table()

/opt/anaconda3/envs/py_experimenter/lib/python3.9/site-packages/codecarbon/output.py:168: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame.from_records([dict(data.values)])])
/opt/anaconda3/envs/py_experimenter/lib/python3.9/site-packages/codecarbon/output.py:168: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame.from_records([dict(data.values)])])
/opt/anaconda3/envs/py_experimenter/lib/python3.9/site-packages/codecarbon/output.py:168: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame.from_records([dict(data.values)])])
/opt/anaconda3/envs/py_experimenter/lib/python3.9/site-packages/codecarbon/output.py:168: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame.from_records([dict(data.values)])])
/opt/anaconda3/envs/py_experimenter/lib/python3.9/site-packages/codecarbon/output.py:168: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame.from_records([dict(data.values)])])
/opt/anaconda3/envs/py_experimenter/lib/python3.9/site-packages/codecarbon/output.py:168: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame.from_records([dict(data.values)])])
/opt/anaconda3/envs/py_experimenter/lib/python3.9/site-packages/codecarbon/output.py:168: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame.from_records([dict(data.values)])])
/opt/anaconda3/envs/py_experimenter/lib/python3.9/site-packages/codecarbon/output.py:168: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame.from_records([dict(data.values)])])
/opt/anaconda3/envs/py_experimenter/lib/python3.9/site-packages/codecarbon/output.py:168: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame.from_records([dict(data.values)])])
/opt/anaconda3/envs/py_experimenter/lib/python3.9/site-packages/codecarbon/output.py:168: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame.from_records([dict(data.values)])])
/opt/anaconda3/envs/py_experimenter/lib/python3.9/site-packages/codecarbon/output.py:168: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame.from_records([dict(data.values)])])
/opt/anaconda3/envs/py_experimenter/lib/python3.9/site-packages/codecarbon/output.py:168: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame.from_records([dict(data.values)])])
2025-10-07 16:53:43,116  | py-experimenter - ERROR    | Traceback (most recent call last):
  File "/Users/lukasfehring/Desktop/library-development/py_experimenter/py_experimenter/experimenter.py", line 444, in _execute_experiment
    final_status = experiment_function(keyfield_values, result_processor, self.config.custom_configuration.custom_values)
  File "/var/folders/3w/xg6_gz354xg5vfw2z0tx7prm0000gn/T/ipykernel_21379/1244630566.py", line 31, in run_ml
    raise ValueError("Example error")
ValueError: Example error

/opt/anaconda3/envs/py_experimenter/lib/python3.9/site-packages/codecarbon/output.py:168: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame.from_records([dict(data.values)])])
2025-10-07 16:53:43,156  | py-experimenter - INFO     | All configured executions finished.

,ID,dataset,cross_validation_splits,seed,kernel,creation_date,status,start_date,name,machine,pipeline,train_f1,train_accuracy,test_f1,test_accuracy,end_date,error
0,1,iris,5,2,linear,2025-10-07 16:52:54,done,2025-10-07 16:52:55,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.971667,0.971667,0.966667,0.966667,2025-10-07 16:53:00,None
1,2,iris,5,4,linear,2025-10-07 16:52:54,done,2025-10-07 16:53:00,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.971667,0.971667,0.966667,0.966667,2025-10-07 16:53:04,None
2,3,iris,5,6,linear,2025-10-07 16:52:54,done,2025-10-07 16:53:04,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.971667,0.971667,0.966667,0.966667,2025-10-07 16:53:07,None
3,4,iris,5,2,poly,2025-10-07 16:52:54,done,2025-10-07 16:53:07,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.936667,0.936667,0.933333,0.933333,2025-10-07 16:53:11,None
4,5,iris,5,4,poly,2025-10-07 16:52:54,done,2025-10-07 16:53:11,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.936667,0.936667,0.933333,0.933333,2025-10-07 16:53:14,None
5,6,iris,5,6,poly,2025-10-07 16:52:54,done,2025-10-07 16:53:14,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.936667,0.936667,0.933333,0.933333,2025-10-07 16:53:18,None
6,7,iris,5,2,rbf,2025-10-07 16:52:54,done,2025-10-07 16:53:18,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.975000,0.975000,0.966667,0.966667,2025-10-07 16:53:21,None
7,8,iris,5,4,rbf,2025-10-07 16:52:54,done,2025-10-07 16:53:21,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.975000,0.975000,0.966667,0.966667,2025-10-07 16:53:25,None
8,9,iris,5,6,rbf,2025-10-07 16:52:54,done,2025-10-07 16:53:25,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.975000,0.975000,0.966667,0.966667,2025-10-07 16:53:28,None
9,10,iris,5,2,sigmoid,2025-10-07 16:52:54,done,2025-10-07 16:53:28,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.896667,0.896667,0.893333,0.893333,2025-10-07 16:53:32,None
10,11,iris,5,4,sigmoid,2025-10-07 16:52:54,done,2025-10-07 16:53:32,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.896667,0.896667,0.893333,0.893333,2025-10-07 16:53:35,None
11,12,iris,5,6,sigmoid,2025-10-07 16:52:54,done,2025-10-07 16:53:35,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.896667,0.896667,0.893333,0.893333,2025-10-07 16:53:39,None
12,13,error_dataset,3,42,linear,2025-10-07 16:52:55,error,2025-10-07 16:53:39,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",NaN,NaN,NaN,NaN,2025-10-07 16:53:43,"Traceback (most recent call last):\n File ""/U..."

### Add Experiment and Execute
For various usecases it might be usefull to add a singular experiment and immidiately start its execution. An example of this is given below.

In [6]:
experimenter.add_experiment_and_execute({'dataset': 'iris', 'cross_validation_splits': 5, 'seed': 17, 'kernel':'linear'}, run_ml)

2025-10-07 16:53:43,173  | py-experimenter - INFO     | Experiment with id 14 successfully added to database for immediate execution.
[codecarbon INFO @ 16:53:43] [setup] RAM Tracking...
[codecarbon INFO @ 16:53:43] [setup] GPU Tracking...
[codecarbon INFO @ 16:53:43] No GPU found.
[codecarbon INFO @ 16:53:43] [setup] CPU Tracking...
[codecarbon WARNING @ 16:53:43] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon INFO @ 16:53:43] CPU Model on constant consumption mode: Apple M1 Pro
[codecarbon INFO @ 16:53:43] >>> Tracker's metadata:
[codecarbon INFO @ 16:53:43]   Platform system: macOS-15.5-arm64-arm-64bit
[codecarbon INFO @ 16:53:43]   Python version: 3.9.18
[codecarbon INFO @ 16:53:43]   CodeCarbon version: 2.3.4
[codecarbon INFO @ 16:53:43]   Available RAM : 32.000 GB
[codecarbon INFO @ 16:53:43]   CPU count: 10
[codecarbon INFO @ 16:53:43]   CPU model: Apple M1 Pro
[codecarbon INFO @ 16:53:43]   GPU count: None
[codecarbon INFO @ 16:53:43]   GPU model: None
[codecarbon INFO @ 16:53:46] Energy consumed for RAM : 0.000000 kWh. RAM Power : 12.0 W
[codecarbon INFO @ 16:53:46] Energy consumed for all CPUs : 0.000000 kWh. Total CPU Power : 5.0 W
[codecarbon INFO @ 16:53:46] 0.000000 kWh of electricity used since the beginning.
2025-10-07 16:53:46,686  | py-experimenter - INFO     | Experiment with id 14 successfully executed.

### Restart Failed Experiments

As experiments fail at some time, those experiments were reset for another try with `reset_experiments()`. The `status` describes which table rows should be replace. In this example all failed experiments, i.e. having `status==error`, are reset. Experiments can also be reset based on multiple status by simply passing a list of status, e.g. `experimenter.reset_experiments('error', 'done')`. In that case, all experiments with status 'error' or 'done' will be reset.

Now all remaining experiments are executed due to `max_experiments=-1`. Note that the `random_order` parameter is set to `False` by default meaning they are executed in orer of increasing id. 
The first parameter, i.e. `run_ml`, relates to the actual method that should be executed with the given keyfields of the table.

In [7]:
experimenter.reset_experiments('error')

# showing database table
experimenter.get_table()

2025-10-07 16:53:46,694  | py-experimenter - INFO     | 1 rows successfully added to database. 0 rows were skipped.
2025-10-07 16:53:46,695  | py-experimenter - INFO     | 1 experiments with status error were reset

,ID,dataset,cross_validation_splits,seed,kernel,creation_date,status,start_date,name,machine,pipeline,train_f1,train_accuracy,test_f1,test_accuracy,end_date,error
0,1,iris,5,2,linear,2025-10-07 16:52:54,done,2025-10-07 16:52:55,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.971667,0.971667,0.966667,0.966667,2025-10-07 16:53:00,None
1,2,iris,5,4,linear,2025-10-07 16:52:54,done,2025-10-07 16:53:00,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.971667,0.971667,0.966667,0.966667,2025-10-07 16:53:04,None
2,3,iris,5,6,linear,2025-10-07 16:52:54,done,2025-10-07 16:53:04,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.971667,0.971667,0.966667,0.966667,2025-10-07 16:53:07,None
3,4,iris,5,2,poly,2025-10-07 16:52:54,done,2025-10-07 16:53:07,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.936667,0.936667,0.933333,0.933333,2025-10-07 16:53:11,None
4,5,iris,5,4,poly,2025-10-07 16:52:54,done,2025-10-07 16:53:11,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.936667,0.936667,0.933333,0.933333,2025-10-07 16:53:14,None
5,6,iris,5,6,poly,2025-10-07 16:52:54,done,2025-10-07 16:53:14,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.936667,0.936667,0.933333,0.933333,2025-10-07 16:53:18,None
6,7,iris,5,2,rbf,2025-10-07 16:52:54,done,2025-10-07 16:53:18,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.975000,0.975000,0.966667,0.966667,2025-10-07 16:53:21,None
7,8,iris,5,4,rbf,2025-10-07 16:52:54,done,2025-10-07 16:53:21,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.975000,0.975000,0.966667,0.966667,2025-10-07 16:53:25,None
8,9,iris,5,6,rbf,2025-10-07 16:52:54,done,2025-10-07 16:53:25,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.975000,0.975000,0.966667,0.966667,2025-10-07 16:53:28,None
9,10,iris,5,2,sigmoid,2025-10-07 16:52:54,done,2025-10-07 16:53:28,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.896667,0.896667,0.893333,0.893333,2025-10-07 16:53:32,None
10,11,iris,5,4,sigmoid,2025-10-07 16:52:54,done,2025-10-07 16:53:32,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.896667,0.896667,0.893333,0.893333,2025-10-07 16:53:35,None
11,12,iris,5,6,sigmoid,2025-10-07 16:52:54,done,2025-10-07 16:53:35,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.896667,0.896667,0.893333,0.893333,2025-10-07 16:53:39,None
12,14,iris,5,17,linear,2025-10-07 16:53:43,done,None,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.971667,0.971667,0.966667,0.966667,2025-10-07 16:53:46,None
13,15,error_dataset,3,42,linear,2025-10-07 16:53:46,created,None,None,None,None,NaN,NaN,NaN,NaN,None,None

After the reset of failed experiments, they can be executed again as described above.

In [8]:
experimenter.execute(run_ml, max_experiments=-1)

# showing database table
experimenter.get_table()

2025-10-07 16:53:50,218  | py-experimenter - ERROR    | Traceback (most recent call last):
  File "/Users/lukasfehring/Desktop/library-development/py_experimenter/py_experimenter/experimenter.py", line 444, in _execute_experiment
    final_status = experiment_function(keyfield_values, result_processor, self.config.custom_configuration.custom_values)
  File "/var/folders/3w/xg6_gz354xg5vfw2z0tx7prm0000gn/T/ipykernel_21379/1244630566.py", line 31, in run_ml
    raise ValueError("Example error")
ValueError: Example error

/opt/anaconda3/envs/py_experimenter/lib/python3.9/site-packages/codecarbon/output.py:168: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame.from_records([dict(data.values)])])
2025-10-07 16:53:50,252  | py-experimenter - INFO     | All configured executions finished.

,ID,dataset,cross_validation_splits,seed,kernel,creation_date,status,start_date,name,machine,pipeline,train_f1,train_accuracy,test_f1,test_accuracy,end_date,error
0,1,iris,5,2,linear,2025-10-07 16:52:54,done,2025-10-07 16:52:55,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.971667,0.971667,0.966667,0.966667,2025-10-07 16:53:00,None
1,2,iris,5,4,linear,2025-10-07 16:52:54,done,2025-10-07 16:53:00,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.971667,0.971667,0.966667,0.966667,2025-10-07 16:53:04,None
2,3,iris,5,6,linear,2025-10-07 16:52:54,done,2025-10-07 16:53:04,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.971667,0.971667,0.966667,0.966667,2025-10-07 16:53:07,None
3,4,iris,5,2,poly,2025-10-07 16:52:54,done,2025-10-07 16:53:07,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.936667,0.936667,0.933333,0.933333,2025-10-07 16:53:11,None
4,5,iris,5,4,poly,2025-10-07 16:52:54,done,2025-10-07 16:53:11,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.936667,0.936667,0.933333,0.933333,2025-10-07 16:53:14,None
5,6,iris,5,6,poly,2025-10-07 16:52:54,done,2025-10-07 16:53:14,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.936667,0.936667,0.933333,0.933333,2025-10-07 16:53:18,None
6,7,iris,5,2,rbf,2025-10-07 16:52:54,done,2025-10-07 16:53:18,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.975000,0.975000,0.966667,0.966667,2025-10-07 16:53:21,None
7,8,iris,5,4,rbf,2025-10-07 16:52:54,done,2025-10-07 16:53:21,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.975000,0.975000,0.966667,0.966667,2025-10-07 16:53:25,None
8,9,iris,5,6,rbf,2025-10-07 16:52:54,done,2025-10-07 16:53:25,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.975000,0.975000,0.966667,0.966667,2025-10-07 16:53:28,None
9,10,iris,5,2,sigmoid,2025-10-07 16:52:54,done,2025-10-07 16:53:28,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.896667,0.896667,0.893333,0.893333,2025-10-07 16:53:32,None
10,11,iris,5,4,sigmoid,2025-10-07 16:52:54,done,2025-10-07 16:53:32,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.896667,0.896667,0.893333,0.893333,2025-10-07 16:53:35,None
11,12,iris,5,6,sigmoid,2025-10-07 16:52:54,done,2025-10-07 16:53:35,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.896667,0.896667,0.893333,0.893333,2025-10-07 16:53:39,None
12,14,iris,5,17,linear,2025-10-07 16:53:43,done,None,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",0.971667,0.971667,0.966667,0.966667,2025-10-07 16:53:46,None
13,15,error_dataset,3,42,linear,2025-10-07 16:53:46,error,2025-10-07 16:53:46,example_notebook,lukass-MacBook-Pro.local,"Pipeline(steps=[('standardscaler', StandardSca...",NaN,NaN,NaN,NaN,2025-10-07 16:53:50,"Traceback (most recent call last):\n File ""/U..."

### Generating Result Table


The table containes single experiment results. Those can be aggregated, e.g. to generate the mean over all seeds.

In [9]:
result_table_agg = experimenter.get_table().groupby(['dataset']).mean(numeric_only = True)
result_table_agg

,ID,cross_validation_splits,seed,train_f1,train_accuracy,test_f1,test_accuracy
dataset,,,,,,,
error_dataset,15.000000,3.0,42.0,NaN,NaN,NaN,NaN
iris,7.076923,5.0,5.0,0.947051,0.947051,0.942051,0.942051

### Printing LaTex Table

As `pandas.Dataframe`s can easily be printed as LaTex table, here is an example code for one of the above result columns.

In [10]:
print(result_table_agg[['test_f1']].style.to_latex())

\begin{tabular}{lr}
 & test_f1 \\
dataset &  \\
error_dataset & nan \\
iris & 0.942051 \\
\end{tabular}

### CodeCarbon
[CodeCarbon](https://tornede.github.io/py_experimenter/usage/experiment_configuration_file.html#codecarbon) is integrated into `PyExperimenter` to provide information about the carbon emissions of experiments. `CodeCarbon` will create a table with suffix `_codecarbon` in the database, each row containing information about the carbon emissions of a single experiment.

In [11]:
experimenter.get_codecarbon_table()

,ID,experiment_id,codecarbon_timestamp,project_name,run_id,duration_seconds,emissions_kg,emissions_rate_kg_sec,cpu_power_watt,gpu_power_watt,...,cpu_model,gpu_count,gpu_model,longitude,latitude,ram_total_size,tracking_mode,on_cloud,power_usage_efficiency,offline_mode
0,1,1,2025-10-07T16:53:00,codecarbon,3bdb3849-0119-427b-8624-45f05d8f2b82,0.059896,2.866257e-08,4.785410e-07,5.0,0.0,...,Apple M1 Pro,None,None,13.2807,52.4552,32.0,process,N,1.0,0
1,2,2,2025-10-07T16:53:04,codecarbon,10e659b4-cbbc-4647-b624-f9ce839e3597,0.060600,2.933101e-08,4.840098e-07,5.0,0.0,...,Apple M1 Pro,None,None,13.2807,52.4552,32.0,process,N,1.0,0
2,3,3,2025-10-07T16:53:07,codecarbon,b3bd32ce-0464-432f-be4f-f095a30d1101,0.056495,2.731377e-08,4.834708e-07,5.0,0.0,...,Apple M1 Pro,None,None,13.2807,52.4552,32.0,process,N,1.0,0
3,4,4,2025-10-07T16:53:11,codecarbon,e0a7f20d-3560-4bcb-b507-23089441aec1,0.062485,3.014664e-08,4.824621e-07,5.0,0.0,...,Apple M1 Pro,None,None,13.2807,52.4552,32.0,process,N,1.0,0
4,5,5,2025-10-07T16:53:14,codecarbon,74313b72-dfba-470f-8c3b-2cacaad1fdf1,0.066115,3.221437e-08,4.872500e-07,5.0,0.0,...,Apple M1 Pro,None,None,13.2807,52.4552,32.0,process,N,1.0,0
5,6,6,2025-10-07T16:53:18,codecarbon,5ae4c624-8986-4f63-bc69-b06320fe58c2,0.059146,2.878689e-08,4.867095e-07,5.0,0.0,...,Apple M1 Pro,None,None,13.2807,52.4552,32.0,process,N,1.0,0
6,7,7,2025-10-07T16:53:21,codecarbon,298ad386-e5fe-4282-a5ca-fc0f34f4d125,0.060189,2.921150e-08,4.853295e-07,5.0,0.0,...,Apple M1 Pro,None,None,13.2807,52.4552,32.0,process,N,1.0,0
7,8,8,2025-10-07T16:53:25,codecarbon,b7b02872-dc56-4a0a-8285-ae46ffaed573,0.063996,3.105273e-08,4.852268e-07,5.0,0.0,...,Apple M1 Pro,None,None,13.2807,52.4552,32.0,process,N,1.0,0
8,9,9,2025-10-07T16:53:28,codecarbon,99feaf20-d0b3-40ac-94a3-b794ba8da0a9,0.065176,3.175808e-08,4.872665e-07,5.0,0.0,...,Apple M1 Pro,None,None,13.2807,52.4552,32.0,process,N,1.0,0
9,10,10,2025-10-07T16:53:32,codecarbon,05504cad-4dab-495f-aa1c-1fd49dc0e4e0,0.062270,3.016858e-08,4.844807e-07,5.0,0.0,...,Apple M1 Pro,None,None,13.2807,52.4552,32.0,process,N,1.0,0
10,11,11,2025-10-07T16:53:35,codecarbon,1dbd3a50-345d-4114-86ba-a1075bec4fd7,0.059693,2.881586e-08,4.827335e-07,5.0,0.0,...,Apple M1 Pro,None,None,13.2807,52.4552,32.0,process,N,1.0,0
11,12,12,2025-10-07T16:53:39,codecarbon,7c3664a5-a324-43d2-93ea-3f9118b64889,0.058372,2.841602e-08,4.868109e-07,5.0,0.0,...,Apple M1 Pro,None,None,13.2807,52.4552,32.0,process,N,1.0,0
12,13,13,2025-10-07T16:53:43,codecarbon,da44f379-c280-42f7-b3d4-84820dab957b,0.041853,1.903773e-08,4.548718e-07,5.0,0.0,...,Apple M1 Pro,None,None,13.2807,52.4552,32.0,process,N,1.0,0
13,14,14,2025-10-07T16:53:46,codecarbon,c0a5200a-c424-4c20-8d5f-2b4c5f4c1c0b,0.049167,7.406564e-08,1.506405e-06,5.0,0.0,...,Apple M1 Pro,None,None,13.2807,52.4552,32.0,machine,N,1.0,0
14,15,15,2025-10-07T16:53:50,codecarbon,e265dbe4-7912-4dae-a3e4-713796130391,0.038966,1.754694e-08,4.503149e-07,5.0,0.0,...,Apple M1 Pro,None,None,13.2807,52.4552,32.0,process,N,1.0,0

#### Aggregating CodeCarbon Results

The carbon emission information of `CodeCarbon` can be easily aggregated via `pandas.Dataframe`.

In [12]:
carbon_emissions = experimenter.get_codecarbon_table().groupby(['project_name']).sum(numeric_only = True)
carbon_emissions

,ID,experiment_id,duration_seconds,emissions_kg,emissions_rate_kg_sec,cpu_power_watt,gpu_power_watt,ram_power_watt,cpu_energy_kw,gpu_energy_kw,ram_energy_kw,energy_consumed_kw,cpu_count,ram_total_size,power_usage_efficiency,offline_mode
project_name,,,,,,,,,,,,,,,,
codecarbon,120,120,0.864419,4.665283e-07,0.000008,75.0,0.0,13.093786,0.000001,0.0,1.540988e-07,0.000001,150.0,480.0,15.0,0

#### Printing CodeCarbon Results as LaTex Table

Furthermore, the resulting `pandas.Dataframe` can easily be printed as LaTex table.

In [13]:
print(carbon_emissions[['energy_consumed_kw', 'emissions_kg']].style.to_latex())

\begin{tabular}{lrr}
 & energy_consumed_kw & emissions_kg \\
project_name &  &  \\
codecarbon & 0.000001 & 0.000000 \\
\end{tabular}